### ISSUE TITLE
Hey I just wanted to know how you run the program

### ISSUE THREAD

**Issue by tusharecmc** [amaydubey/spring-job-portal#1]

**Comment by tusharecmc** [comment]
hey I just wanted to know how can I run your Project.

**Comment by imajay777** [comment]
Unable to run application.java...Any solutions found?

**Comment by tusharecmc** [comment]
application.properties files have some errors there are colon(:) used instead of equal(=). You need to correct that and also create the database separately before running the program. It should work.

**Comment by imajay777** [comment]
Changed some colons but not working..Can you please mail me application.properties file to gs.ajaysharma@gmail.com

**Comment by imajay777** [comment]
When i click on run as i don't get any run as application or run on server option in eclipse....please help!!

**Comment by amaydubey** [comment]
You need to run `src/main/java/com/baeldung/spring/Application.java` as a Java application.
